
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150326 (SVN rev 63)
//----------------------------------------------------

package edu.cmu.cs464.p3.modulelang.parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IDENT = 8;
  public static final int COLON = 4;
  public static final int STAR = 7;
  public static final int HAS = 2;
  public static final int EOF = 0;
  public static final int DOT = 6;
  public static final int error = 1;
  public static final int END = 3;
  public static final int IMPORT = 5;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "HAS",
  "END",
  "COLON",
  "IMPORT",
  "DOT",
  "STAR",
  "IDENT"
  };
}

